"""Self-contained Blender script: builds the Propeller tensegrity and
animates a camera flying through its three loops as a roller-coaster.

Generated by `cargo test --release --lib test_propeller_blender_export`.
Edit the source (src/propeller_blender_export.rs) and re-run that test
to regenerate — don't hand-edit the constants below.

Usage:
  - Open Blender with an empty scene.
  - Open this file in the scripting workspace and Run Script (Alt+P), or
    `blender --python scripts/propeller_blender.py`.

Conventions:
  - Coordinates are in metres, Y-up (simulation convention). Blender's
    default Z-up world is rotated 90° around X on import so the
    structure stands the right way.
  - One lap of the camera = 60 seconds at 24 fps.
"""

import bpy
import math
import os
import mathutils
from mathutils import Vector

# ── Knobs ────────────────────────────────────────────────────────────────────
FPS = 24
LAP_SECONDS = 60.0
TOTAL_FRAMES = int(FPS * LAP_SECONDS)

# PUSH_RADIUS / PULL_RADIUS come from the fabric's actual connector
# dimensions (in metres). Tweak the multipliers if you want fatter
# struts for stylised renders.
PUSH_RADIUS_SCALE = 1.0
PULL_RADIUS_SCALE = 0.25  # quarter of the physical cable thickness — these
                          # are tension lines and read best thin.
BANK_GAIN = 0.6               # how much to tilt into corners (radians per
                              # unit curvature); 0 = no banking

# Look-ahead for the camera target, as a fraction of the loop.
LOOKAHEAD_FRACTION = 0.04

# Evening-scene knobs. Coloured spots are placed at this distance from
# the centroid (as a multiple of the bounding radius), and the world
# HDRI is dimmed by HDRI_STRENGTH.
LIGHT_DISTANCE_FACTOR = 1.6
HDRI_STRENGTH = 0.08

CENTROID = (0.00028, 7.30281, -0.00027)
BOUNDING_RADIUS = 7.77051
PUSH_RADIUS = 0.02000
PULL_RADIUS = 0.00300

JOINTS = [
    (-1.11209, 5.71586, -0.09174),
    (1.20065, 7.31462, -0.88549),
    (-1.27348, 6.52711, 0.95809),
    (1.05247, 8.09849, 0.17028),
    (0.47724, 5.71583, 1.00876),
    (-1.36653, 7.31463, -0.59723),
    (1.46712, 6.52709, 0.62363),
    (-0.37811, 8.09851, -0.99678),
    (0.63564, 5.71585, -0.91790),
    (0.16670, 7.31460, 1.48189),
    (-0.19283, 6.52713, -1.58258),
    (-0.67350, 8.09848, 0.82569),
    (-1.16418, 6.70959, 0.35152),
    (-2.30082, 5.82745, -2.38304),
    (-0.32559, 7.50413, -1.04047),
    (-2.99535, 6.01821, -1.36785),
    (-0.14071, 5.78610, -0.73651),
    (-2.62069, 7.01813, -2.08853),
    (-0.73763, 7.50412, 0.80205),
    (0.31375, 6.01811, 3.27776),
    (-0.56683, 5.78608, 0.48990),
    (-0.49772, 7.01805, 3.31367),
    (1.06404, 7.50410, 0.23761),
    (2.68243, 6.01821, -1.91081),
    (0.70834, 5.78607, 0.24572),
    (3.11923, 7.01811, -1.22597),
    (0.41012, 6.33821, 0.94978),
    (2.56609, 8.31641, 1.93647),
    (-0.04671, 7.98670, 0.60402),
    (2.26628, 7.15588, 2.48282),
    (0.61812, 6.33823, -0.83027),
    (0.39461, 8.31647, -3.19070),
    (0.54710, 7.98670, -0.26173),
    (1.01769, 7.15595, -3.20426),
    (-1.02745, 6.33823, -0.12038),
    (-2.95985, 8.31645, 1.25350),
    (-0.49956, 7.98671, -0.34310),
    (-3.28315, 7.15595, 0.72064),
    (-2.15522, 5.57785, -1.42939),
    (-4.21944, 7.04096, -2.57918),
    (-1.73662, 6.60202, -2.24350),
    (-4.46307, 6.02286, -2.32310),
    (-0.15962, 5.57778, 2.58095),
    (-0.12328, 7.04084, 4.94356),
    (-1.07397, 6.60195, 2.62552),
    (0.22032, 6.02274, 5.02649),
    (2.31565, 5.57784, -1.15247),
    (4.34353, 7.04096, -2.36520),
    (2.81140, 6.60198, -0.38287),
    (4.24356, 6.02286, -2.70426),
    (1.62101, 8.40333, 1.72628),
    (3.14689, 7.84165, 4.00200),
    (1.31499, 7.31431, 2.16429),
    (2.67586, 8.93629, 3.97475),
    (0.68514, 8.40339, -2.26715),
    (1.89302, 7.84174, -4.72647),
    (1.21749, 7.31437, -2.22115),
    (2.10495, 8.93639, -4.30490),
    (-2.30531, 8.40338, 0.54011),
    (-5.03908, 7.84172, 0.72374),
    (-2.53166, 7.31437, 0.05604),
    (-4.77996, 8.93638, 0.32945),
    (-3.45700, 7.05494, -2.94445),
    (-5.86576, 6.82706, -2.34313),
    (-3.83431, 5.91818, -2.85837),
    (-5.57034, 7.71904, -2.71111),
    (-0.82084, 7.05483, 4.46590),
    (0.90430, 6.82692, 6.25129),
    (-0.55761, 5.91806, 4.74958),
    (0.43788, 7.71890, 6.17946),
    (4.27865, 7.05491, -1.52227),
    (4.96230, 6.82706, -3.90898),
    (4.39272, 5.91816, -1.89210),
    (5.13330, 7.71904, -3.46912),
    (2.50009, 7.51679, 3.58017),
    (2.75016, 8.64942, 5.78093),
    (2.03366, 8.55996, 3.58122),
    (2.91271, 7.53019, 5.71688),
    (1.85113, 7.51687, -3.95542),
    (3.63200, 8.64954, -5.27233),
    (2.08525, 8.56005, -3.55198),
    (3.49526, 7.53030, -5.38112),
    (-4.35037, 7.51687, 0.37449),
    (-6.38131, 8.64953, -0.50933),
    (-4.11806, 8.56005, -0.02997),
    (-6.40713, 7.53029, -0.33654),
    (-5.54836, 6.23858, -2.67176),
    (-6.38195, 8.10787, -1.71233),
    (-5.43899, 7.24523, -3.23004),
    (-6.61916, 7.21411, -1.31196),
    (0.46101, 6.23843, 6.14070),
    (1.70866, 8.10773, 6.38299),
    (-0.07718, 7.24508, 6.32516),
    (2.17400, 7.21399, 6.38822),
    (5.08815, 6.23856, -3.46980),
    (4.67417, 8.10787, -4.67142),
    (5.51701, 7.24519, -3.09594),
    (4.44603, 7.21413, -5.07705),
    (2.34832, 8.79483, 5.18352),
    (1.72320, 7.40073, 6.83711),
    (2.58722, 7.82388, 5.10218),
    (1.18340, 8.34443, 6.77883),
    (3.31555, 8.79496, -4.62563),
    (5.06018, 7.40088, -4.91108),
    (3.12568, 7.82400, -4.79189),
    (5.27960, 8.34457, -4.41444),
    (-5.66301, 8.79495, -0.55863),
    (-6.78254, 7.40088, -1.92680),
    (-5.71203, 7.82399, -0.31107),
    (-6.46214, 8.34456, -2.36513),
    (-0.91989, 7.18053, -1.08902),
    (-0.48249, 7.18049, 1.34098),
    (-2.31264, 6.73641, -1.17516),
    (1.40323, 7.18050, -0.25280),
    (0.27782, 6.70959, -1.18463),
    (0.88715, 6.70957, 0.83224),
    (-0.91270, 5.82736, 3.18388),
    (0.13927, 6.73633, 2.59021),
    (3.21433, 5.82741, -0.80173),
    (2.17420, 6.73641, -1.41590),
    (1.47408, 8.15326, 2.67836),
    (2.42064, 7.42333, 1.57942),
    (1.58314, 8.15334, -2.61594),
    (0.15814, 7.42339, -2.88623),
    (-3.05638, 8.15334, -0.06318),
    (-2.57793, 7.42336, 1.30600),
    (-4.07487, 6.60669, -3.31828),
    (-3.73821, 6.45136, -2.07789),
    (-0.83565, 6.60655, 5.18789),
    (0.07024, 6.45127, 4.27614),
    (4.91132, 6.60665, -1.87046),
    (3.66877, 6.45137, -2.19912),
    (2.22423, 8.03252, 4.26905),
    (3.10244, 8.47297, 3.42210),
    (2.58563, 8.03261, -4.06094),
    (1.41305, 8.47307, -4.39801),
    (-4.80904, 8.03262, -0.20883),
    (-4.51466, 8.47305, 0.97520),
    (-6.00817, 6.79687, -2.95907),
    (-5.14019, 7.02567, -2.67836),
    (0.44209, 6.79672, 6.68257),
    (0.25120, 7.02553, 5.79055),
    (5.56690, 6.79684, -3.72435),
    (4.88984, 7.02566, -3.11301),
    (2.11353, 8.20133, 5.67671),
    (3.13614, 8.14781, 5.35230),
    (3.86006, 8.20147, -4.66891),
    (3.06781, 8.14792, -5.39231),
    (-5.97274, 8.20146, -1.00855),
    (-6.20313, 8.14791, 0.03926),
    (-6.83453, 8.12989, -1.80375),
    (1.85576, 8.12974, 6.82065),
    (4.97964, 8.12989, -5.01763),
    (1.43339, 7.38562, 6.54001),
    (4.94779, 7.38576, -4.51154),
    (-6.38029, 7.38576, -2.02924),
]

PUSHES = [
    (0, 1),
    (2, 3),
    (4, 5),
    (6, 7),
    (8, 9),
    (10, 11),
    (32, 33),
    (30, 31),
    (110, 122),
    (36, 37),
    (34, 35),
    (111, 124),
    (40, 41),
    (38, 39),
    (112, 126),
    (28, 29),
    (26, 27),
    (113, 120),
    (24, 25),
    (22, 23),
    (114, 118),
    (20, 21),
    (18, 19),
    (115, 116),
    (12, 13),
    (14, 15),
    (16, 17),
    (44, 45),
    (42, 43),
    (117, 128),
    (48, 49),
    (46, 47),
    (119, 130),
    (52, 53),
    (50, 51),
    (121, 132),
    (56, 57),
    (54, 55),
    (123, 134),
    (60, 61),
    (58, 59),
    (125, 136),
    (64, 65),
    (62, 63),
    (127, 138),
    (68, 69),
    (66, 67),
    (129, 140),
    (72, 73),
    (70, 71),
    (131, 142),
    (76, 77),
    (74, 75),
    (133, 144),
    (80, 81),
    (78, 79),
    (135, 146),
    (84, 85),
    (82, 83),
    (137, 148),
    (88, 89),
    (86, 87),
    (139, 150),
    (92, 93),
    (90, 91),
    (141, 151),
    (96, 97),
    (94, 95),
    (143, 152),
    (100, 101),
    (98, 99),
    (145, 153),
    (104, 105),
    (102, 103),
    (147, 154),
    (108, 109),
    (106, 107),
    (149, 155),
]

PULLS = [
    (8, 0),
    (4, 8),
    (0, 4),
    (12, 15),
    (14, 17),
    (16, 13),
    (20, 116),
    (18, 21),
    (115, 19),
    (12, 0),
    (12, 5),
    (14, 5),
    (14, 10),
    (16, 10),
    (16, 0),
    (24, 118),
    (22, 25),
    (114, 23),
    (115, 4),
    (115, 9),
    (18, 9),
    (18, 2),
    (20, 2),
    (20, 4),
    (28, 120),
    (26, 29),
    (113, 27),
    (114, 8),
    (114, 1),
    (22, 1),
    (22, 6),
    (24, 6),
    (24, 8),
    (32, 122),
    (30, 33),
    (110, 31),
    (113, 3),
    (113, 6),
    (26, 6),
    (26, 9),
    (28, 9),
    (28, 3),
    (36, 124),
    (34, 37),
    (111, 35),
    (110, 7),
    (110, 10),
    (30, 10),
    (30, 1),
    (32, 1),
    (32, 7),
    (40, 126),
    (38, 41),
    (112, 39),
    (111, 11),
    (111, 2),
    (34, 2),
    (34, 5),
    (36, 5),
    (36, 11),
    (44, 128),
    (42, 45),
    (117, 43),
    (112, 17),
    (112, 15),
    (38, 15),
    (38, 13),
    (40, 13),
    (40, 17),
    (48, 130),
    (46, 49),
    (119, 47),
    (117, 21),
    (117, 19),
    (42, 19),
    (42, 116),
    (44, 116),
    (44, 21),
    (52, 132),
    (50, 53),
    (121, 51),
    (119, 25),
    (119, 23),
    (46, 23),
    (46, 118),
    (48, 118),
    (48, 25),
    (56, 134),
    (54, 57),
    (123, 55),
    (121, 29),
    (121, 27),
    (50, 27),
    (50, 120),
    (52, 120),
    (52, 29),
    (60, 136),
    (58, 61),
    (125, 59),
    (123, 33),
    (123, 31),
    (54, 31),
    (54, 122),
    (56, 122),
    (56, 33),
    (64, 138),
    (62, 65),
    (127, 63),
    (125, 37),
    (125, 35),
    (58, 35),
    (58, 124),
    (60, 124),
    (60, 37),
    (68, 140),
    (66, 69),
    (129, 67),
    (127, 41),
    (127, 39),
    (62, 39),
    (62, 126),
    (64, 126),
    (64, 41),
    (72, 142),
    (70, 73),
    (131, 71),
    (129, 45),
    (129, 43),
    (66, 43),
    (66, 128),
    (68, 128),
    (68, 45),
    (76, 144),
    (74, 77),
    (133, 75),
    (131, 49),
    (131, 47),
    (70, 47),
    (70, 130),
    (72, 130),
    (72, 49),
    (80, 146),
    (78, 81),
    (135, 79),
    (133, 53),
    (133, 51),
    (74, 51),
    (74, 132),
    (76, 132),
    (76, 53),
    (84, 148),
    (82, 85),
    (137, 83),
    (135, 57),
    (135, 55),
    (78, 55),
    (78, 134),
    (80, 134),
    (80, 57),
    (88, 150),
    (86, 89),
    (139, 87),
    (152, 105),
    (151, 101),
    (150, 109),
    (137, 61),
    (137, 59),
    (82, 59),
    (82, 136),
    (84, 136),
    (84, 61),
    (92, 151),
    (90, 93),
    (141, 91),
    (2, 125),
    (91, 101),
    (91, 153),
    (139, 65),
    (139, 63),
    (86, 63),
    (86, 138),
    (88, 138),
    (88, 65),
    (96, 152),
    (94, 97),
    (143, 95),
    (2, 12),
    (95, 105),
    (95, 154),
    (141, 69),
    (141, 67),
    (90, 67),
    (90, 140),
    (92, 140),
    (92, 69),
    (100, 153),
    (98, 101),
    (145, 99),
    (1, 56),
    (1, 119),
    (1, 113),
    (143, 73),
    (143, 71),
    (94, 71),
    (94, 142),
    (96, 142),
    (96, 73),
    (104, 154),
    (102, 105),
    (147, 103),
    (97, 154),
    (97, 103),
    (152, 103),
    (145, 77),
    (145, 75),
    (98, 75),
    (98, 144),
    (100, 144),
    (100, 77),
    (108, 155),
    (106, 109),
    (149, 107),
    (0, 38),
    (0, 34),
    (0, 20),
    (147, 81),
    (147, 79),
    (102, 79),
    (102, 146),
    (104, 146),
    (104, 81),
    (89, 155),
    (89, 107),
    (150, 107),
    (93, 153),
    (93, 99),
    (151, 99),
    (149, 85),
    (149, 83),
    (106, 83),
    (106, 148),
    (108, 148),
    (108, 85),
    (87, 155),
    (87, 109),
    (2, 44),
    (3, 22),
    (3, 32),
    (3, 50),
    (4, 24),
    (4, 26),
    (4, 42),
    (5, 110),
    (5, 112),
    (5, 60),
    (6, 115),
    (6, 121),
    (6, 48),
    (7, 14),
    (7, 36),
    (7, 54),
    (8, 16),
    (8, 30),
    (8, 46),
    (9, 111),
    (9, 117),
    (9, 52),
    (10, 114),
    (10, 123),
    (10, 40),
    (11, 18),
    (11, 28),
    (11, 58),
    (13, 64),
    (15, 127),
    (17, 62),
    (116, 68),
    (19, 129),
    (21, 66),
    (118, 72),
    (23, 131),
    (25, 70),
    (120, 76),
    (27, 133),
    (29, 74),
    (122, 80),
    (31, 135),
    (33, 78),
    (124, 84),
    (35, 137),
    (37, 82),
    (126, 88),
    (39, 139),
    (41, 86),
    (128, 92),
    (43, 141),
    (45, 90),
    (130, 96),
    (47, 143),
    (49, 94),
    (132, 100),
    (51, 145),
    (53, 98),
    (134, 104),
    (55, 147),
    (57, 102),
    (136, 108),
    (59, 149),
    (61, 106),
    (138, 107),
    (63, 155),
    (65, 109),
    (140, 99),
    (67, 153),
    (69, 101),
    (142, 103),
    (71, 154),
    (73, 105),
    (144, 91),
    (75, 151),
    (77, 93),
    (146, 95),
    (79, 152),
    (81, 97),
    (148, 87),
    (83, 150),
    (85, 89),
    (3, 7),
    (7, 11),
    (11, 3),
]

CAMERA_PATH = [
    (-1.59122, 6.47727, -1.21081),
    (-3.16031, 6.43113, -2.17810),
    (-4.74563, 6.79458, -2.64900),
    (-5.99386, 7.32689, -2.23470),
    (-6.20052, 7.98301, -1.19194),
    (-5.29071, 8.15521, -0.08912),
    (-3.67383, 7.99197, 0.45775),
    (-1.88482, 7.52186, 0.46474),
    (0.00028, 7.30281, -0.00027),
    (1.84437, 6.47725, -0.77330),
    (3.46661, 6.43112, -1.64853),
    (4.66711, 6.79456, -2.78599),
    (4.93247, 7.32689, -4.07414),
    (4.13277, 7.98302, -4.77448),
    (2.72279, 8.15522, -4.53796),
    (1.44073, 7.99198, -3.41114),
    (0.54013, 7.52187, -1.86532),
    (0.00028, 7.30281, -0.00027),
    (-0.25233, 6.47721, 1.98325),
    (-0.30549, 6.43103, 3.82577),
    (0.07934, 6.79445, 5.43416),
    (1.06224, 7.32675, 6.30804),
    (2.06861, 7.98288, 5.96566),
    (2.56877, 8.15511, 4.62633),
    (2.23394, 7.99191, 2.95263),
    (1.34552, 7.52183, 1.39978),
    (0.00028, 7.30281, -0.00027),
]


# ── Helpers ──────────────────────────────────────────────────────────────────

def clear_scene():
    """Remove every object from the active scene — keep the slate clean."""
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for coll in (bpy.data.meshes, bpy.data.curves, bpy.data.cameras,
                 bpy.data.lights, bpy.data.materials):
        for item in list(coll):
            if item.users == 0:
                coll.remove(item)


def make_material(name, rgba, metallic=0.0, roughness=0.5):
    """Principled BSDF — same shader the rest of the project's Blender
    scripts use, so the propeller responds properly to the evening lights."""
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    if bsdf:
        bsdf.inputs["Base Color"].default_value = rgba
        bsdf.inputs["Metallic"].default_value = metallic
        bsdf.inputs["Roughness"].default_value = roughness
    # Viewport solid-mode colour falls back to this:
    mat.diffuse_color = rgba
    return mat


# ── Scripts directory + HDRI ────────────────────────────────────────────────

def _find_scripts_dir():
    """Same logic as scripts/create-environment.py — `__file__` is
    unreliable in Blender's text editor, so try a few likely homes."""
    candidates = []
    try:
        candidates.append(os.path.dirname(os.path.abspath(__file__)))
    except (NameError, OSError):
        pass
    if bpy.data.filepath:
        blend_dir = os.path.dirname(bpy.data.filepath)
        candidates.append(os.path.join(blend_dir, "scripts"))
        candidates.append(os.path.join(blend_dir, "..", "scripts"))
    candidates.append(os.path.expanduser("~/RustroverProjects/tensegrity-lab/scripts"))
    for d in candidates:
        if os.path.isdir(d):
            return os.path.abspath(d)
    return "."


SCRIPT_DIR = _find_scripts_dir()
HDRI_TEXTURE = os.path.join(SCRIPT_DIR, "moonless_golf_4k.exr")


def sim_to_world(p):
    """Sim is Y-up; PropellerRoot rotates by +90° around X to make it
    Z-up. The world-coords version of a sim point (x, y, z) is (x, -z, y)."""
    x, y, z = p
    return (x, -z, y)


def cylinder_between(p1, p2, radius, material, name, end_fill="NGON"):
    """Create a cylinder primitive between two points. `end_fill` can be
    "NGON" (default — flat cap) or "NOTHING" (no end geometry; only safe
    when something else is going to cover the ends)."""
    a = Vector(p1)
    b = Vector(p2)
    vec = b - a
    length = vec.length
    if length < 1e-9:
        return None
    midpoint = (a + b) * 0.5
    bpy.ops.mesh.primitive_cylinder_add(
        radius=radius, depth=length, location=midpoint, end_fill_type=end_fill,
    )
    obj = bpy.context.active_object
    obj.name = name
    # Align the cylinder's local Z axis with `vec`.
    z = Vector((0.0, 0.0, 1.0))
    if vec.length > 0:
        axis = z.cross(vec)
        if axis.length < 1e-9:
            # parallel or anti-parallel
            if vec.dot(z) < 0:
                obj.rotation_euler = (math.pi, 0.0, 0.0)
        else:
            angle = z.angle(vec)
            obj.rotation_mode = "AXIS_ANGLE"
            obj.rotation_axis_angle = (angle, *axis.normalized())
    obj.data.materials.append(material)
    return obj


def build_geometry():
    # Brushed-aluminium struts, warm dielectric cables, joint-balls
    # using the same metal as the struts so they read as natural caps.
    push_mat = make_material("Push", (0.78, 0.78, 0.82, 1.0),
                              metallic=1.0, roughness=0.22)
    pull_mat = make_material("Pull", (0.95, 0.95, 0.95, 1.0),
                              metallic=0.0, roughness=0.4)
    joint_mat = make_material("Joint", (0.72, 0.72, 0.76, 1.0),
                               metallic=1.0, roughness=0.28)
    push_r = PUSH_RADIUS * PUSH_RADIUS_SCALE
    pull_r = PULL_RADIUS * PULL_RADIUS_SCALE
    for i, (a, o) in enumerate(PUSHES):
        cylinder_between(JOINTS[a], JOINTS[o], push_r, push_mat, f"Push.{i:03d}")
    # Pull ends sit inside the joint spheres, so they don't need caps.
    for i, (a, o) in enumerate(PULLS):
        cylinder_between(JOINTS[a], JOINTS[o], pull_r, pull_mat,
                         f"Pull.{i:03d}", end_fill="NOTHING")
    # One sphere per joint, sized to the push radius — covers every
    # cylinder end (both push and pull) where it meets the joint, so
    # the flat cylinder caps and the pull-cable end-disc artefacts
    # disappear behind a clean hemispherical cap.
    for i, p in enumerate(JOINTS):
        bpy.ops.mesh.primitive_uv_sphere_add(
            radius=push_r, segments=16, ring_count=10, location=p,
        )
        obj = bpy.context.active_object
        obj.name = f"Joint.{i:03d}"
        # Smooth shading so the spheres don't show facets.
        for poly in obj.data.polygons:
            poly.use_smooth = True
        obj.data.materials.append(joint_mat)


# ── Camera path ──────────────────────────────────────────────────────────────

def _compute_banking_tilts(points):
    """For each control point i, the tilt that rolls the camera into
    the turn at that point. Signed magnitude of the cross product
    between adjacent tangents, projected onto world-up."""
    pts = [Vector(p) for p in points]
    n = len(pts)
    up = Vector((0.0, 1.0, 0.0))  # sim is Y-up; PropellerRoot rotates it to Z-up
    tilts = [0.0] * n
    for i in range(n):
        prev_t = pts[i] - pts[(i - 1) % n]
        next_t = pts[(i + 1) % n] - pts[i]
        if prev_t.length < 1e-9 or next_t.length < 1e-9:
            continue
        prev_t.normalize()
        next_t.normalize()
        curvature_vec = next_t - prev_t
        # signed lean: positive = roll into right turn
        signed = curvature_vec.dot(prev_t.cross(up))
        tilts[i] = BANK_GAIN * signed
    return tilts


def build_camera_curve():
    """Closed bezier with one control point per *original* path waypoint.
    Blender's AUTO handles need enough spacing between control points to
    produce real curvature — packing in one point per frame (the prior
    bug) collapsed the spline into a polyline. Tilts bank into corners."""
    tilts = _compute_banking_tilts(CAMERA_PATH)

    curve_data = bpy.data.curves.new("CamPath", type="CURVE")
    curve_data.dimensions = "3D"
    curve_data.use_path = True
    curve_data.path_duration = TOTAL_FRAMES
    spline = curve_data.splines.new(type="BEZIER")
    spline.use_cyclic_u = True
    spline.bezier_points.add(len(CAMERA_PATH) - 1)
    for bp, pt, tilt in zip(spline.bezier_points, CAMERA_PATH, tilts):
        bp.co = Vector(pt)
        bp.handle_left_type = "AUTO"
        bp.handle_right_type = "AUTO"
        bp.tilt = tilt

    curve_obj = bpy.data.objects.new("CamPath", curve_data)
    bpy.context.collection.objects.link(curve_obj)
    return curve_obj


def setup_camera(curve_obj):
    """Camera follows the curve. A target Empty follows the same curve
    a small offset ahead, and the camera tracks it — so the camera is
    always looking down the next stretch of track."""
    # Camera
    cam_data = bpy.data.cameras.new("Camera")
    cam_data.lens = 28.0
    cam_obj = bpy.data.objects.new("Camera", cam_data)
    bpy.context.collection.objects.link(cam_obj)
    cam_obj.location = (0.0, 0.0, 0.0)

    follow = cam_obj.constraints.new(type="FOLLOW_PATH")
    follow.target = curve_obj
    follow.use_curve_follow = True
    follow.forward_axis = "FORWARD_Y"
    follow.up_axis = "UP_Z"
    # The follow constraint starts the camera at the path's start at frame 1.

    # Path animation: drive evaluation_time linearly over the lap.
    path_anim = curve_obj.data.animation_data_create()
    action = bpy.data.actions.new("CamPathDrive")
    path_anim.action = action
    fcurve = action.fcurves.new(data_path="eval_time", index=-1)
    fcurve.keyframe_points.add(2)
    fcurve.keyframe_points[0].co = (1, 0)
    fcurve.keyframe_points[0].interpolation = "LINEAR"
    fcurve.keyframe_points[1].co = (TOTAL_FRAMES, TOTAL_FRAMES)
    fcurve.keyframe_points[1].interpolation = "LINEAR"

    # Look-ahead target Empty: same path, offset ahead in evaluation time.
    target_curve = curve_obj.copy()
    target_curve.data = curve_obj.data.copy()
    target_curve.data.name = "CamPathTarget"
    target_curve.name = "CamPathTarget"
    bpy.context.collection.objects.link(target_curve)

    tgt = bpy.data.objects.new("CamTarget", None)
    tgt.empty_display_type = "PLAIN_AXES"
    tgt.empty_display_size = 0.05 * BOUNDING_RADIUS
    bpy.context.collection.objects.link(tgt)
    t_follow = tgt.constraints.new(type="FOLLOW_PATH")
    t_follow.target = target_curve
    t_follow.use_curve_follow = False

    lookahead = int(LOOKAHEAD_FRACTION * TOTAL_FRAMES)
    target_anim = target_curve.data.animation_data_create()
    target_action = bpy.data.actions.new("CamPathTargetDrive")
    target_anim.action = target_action
    t_fc = target_action.fcurves.new(data_path="eval_time", index=-1)
    t_fc.keyframe_points.add(2)
    t_fc.keyframe_points[0].co = (1, lookahead)
    t_fc.keyframe_points[0].interpolation = "LINEAR"
    t_fc.keyframe_points[1].co = (TOTAL_FRAMES, TOTAL_FRAMES + lookahead)
    t_fc.keyframe_points[1].interpolation = "LINEAR"

    track = cam_obj.constraints.new(type="TRACK_TO")
    track.target = tgt
    track.track_axis = "TRACK_NEGATIVE_Z"
    track.up_axis = "UP_Y"

    bpy.context.scene.camera = cam_obj


# ── Evening world + lighting ────────────────────────────────────────────────

def setup_evening_world():
    """World background: night-sky HDRI dimmed for an evening feel, with
    a flat dark-blue fallback if the HDRI file isn't found alongside the
    script."""
    world = bpy.context.scene.world
    if world is None:
        world = bpy.data.worlds.new("World")
        bpy.context.scene.world = world
    world.use_nodes = True
    nodes = world.node_tree.nodes
    links = world.node_tree.links
    nodes.clear()

    output = nodes.new("ShaderNodeOutputWorld")
    output.location = (300, 0)
    background = nodes.new("ShaderNodeBackground")
    background.location = (0, 0)
    background.inputs["Strength"].default_value = HDRI_STRENGTH
    links.new(background.outputs["Background"], output.inputs["Surface"])

    if os.path.exists(HDRI_TEXTURE):
        env_tex = nodes.new("ShaderNodeTexEnvironment")
        env_tex.location = (-300, 0)
        env_tex.image = bpy.data.images.load(HDRI_TEXTURE)
        links.new(env_tex.outputs["Color"], background.inputs["Color"])
        print(f"Loaded HDRI: {HDRI_TEXTURE}")
    else:
        background.inputs["Color"].default_value = (0.02, 0.03, 0.07, 1.0)
        print(f"NOTE: HDRI not found at {HDRI_TEXTURE} — using flat evening blue.")


def build_lighting():
    """Three coloured spotlights at 120° intervals around the propeller's
    bounding sphere (in world coords — these are NOT parented to the
    rotating PropellerRoot, so they stay put while the structure spins
    relative to them), plus a soft moonlight fill from above."""
    cx, cy, cz = sim_to_world(CENTROID)
    distance = BOUNDING_RADIUS * LIGHT_DISTANCE_FACTOR

    colors = [
        ((1.0, 0.18, 0.12), "Red"),
        ((0.12, 1.0, 0.18), "Green"),
        ((0.18, 0.22, 1.0), "Blue"),
    ]
    for i, (color, name) in enumerate(colors):
        angle = i * 2 * math.pi / 3
        pos = Vector((
            cx + math.cos(angle) * distance,
            cy + math.sin(angle) * distance,
            cz,
        ))
        target = Vector((cx, cy, cz))
        direction = target - pos
        rot_quat = direction.to_track_quat("-Z", "Y")

        spot_data = bpy.data.lights.new(f"Spot_{name}", "SPOT")
        spot_data.energy = 8000.0
        spot_data.color = color
        spot_data.spot_size = math.radians(100)
        spot_data.spot_blend = 0.6
        spot_data.shadow_soft_size = 1.5
        spot_obj = bpy.data.objects.new(f"Spot_{name}", spot_data)
        spot_obj.location = pos
        spot_obj.rotation_euler = rot_quat.to_euler()
        bpy.context.collection.objects.link(spot_obj)

    # Soft moonlight fill from above (world Z+).
    sun_data = bpy.data.lights.new("Moonlight", "SUN")
    sun_data.energy = 1.0
    sun_data.color = (0.7, 0.78, 1.0)
    sun_data.angle = math.radians(12)
    sun_obj = bpy.data.objects.new("Moonlight", sun_data)
    sun_obj.location = (cx, cy, cz + distance)
    sun_obj.rotation_euler = (math.radians(15), math.radians(20), 0.0)
    bpy.context.collection.objects.link(sun_obj)


# ── World orientation ────────────────────────────────────────────────────────

def orient_world():
    """Sim is Y-up; Blender's world is Z-up. Wrap the propeller geometry
    in an Empty rotated 90° around X so it stands the right way.
    Lights live in world coords (placed by build_lighting using
    sim_to_world) and stay put when the structure spins around them."""
    parent = bpy.data.objects.new("PropellerRoot", None)
    parent.empty_display_type = "PLAIN_AXES"
    bpy.context.collection.objects.link(parent)
    parent.rotation_euler = (math.pi / 2.0, 0.0, 0.0)
    for obj in list(bpy.context.scene.objects):
        if obj is parent:
            continue
        if obj.type in {"LIGHT"}:
            continue
        if obj.parent is None:
            obj.parent = parent


# ── Entry point ──────────────────────────────────────────────────────────────

def main():
    clear_scene()
    bpy.context.scene.frame_start = 1
    bpy.context.scene.frame_end = TOTAL_FRAMES
    bpy.context.scene.render.fps = FPS

    build_geometry()
    curve = build_camera_curve()
    setup_camera(curve)
    build_lighting()
    setup_evening_world()
    orient_world()

    # Eevee bloom looks nice on the spot beams. (Cycles renders them too;
    # this is a no-op there.)
    eevee = getattr(bpy.context.scene, "eevee", None)
    if eevee is not None and hasattr(eevee, "use_bloom"):
        eevee.use_bloom = True

    print(f"Propeller built — {len(PUSHES)} pushes, {len(PULLS)} pulls, "
          f"{len(CAMERA_PATH)} path waypoints, {TOTAL_FRAMES} frames "
          f"({LAP_SECONDS}s at {FPS}fps).")


if __name__ == "__main__":
    main()

